# Imagem base oficial do Node
FROM node:18

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Porta exposta no container
EXPOSE 3001

# Comando para iniciar o app
CMD ["node", "server.js"]
